name: Deploy Astro to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # Required for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-2

      - name: Install dependencies
        run: npm install

      - name: Build Astro project
        run: npm run build

      - name: Sync files to S3
        run: aws s3 sync ./dist s3://paulpladziewicz --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E31K5YCXZ1B865 --paths "/*"
